sonar.projectKey=in2workspace_eudistack-cert-identifier-service
sonar.organization=in2workspace

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=eudistack-cert-identifier-service

# can be replaced with your desired value
sonar.projectVersion=1.0

# Replace path according to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=api,server

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Files to be excluded from analysis
sonar.exclusions=node_modules/**, server/certs/**, **/.DS_Store

# host url
sonar.host.url=https://sonarcloud.io
